spring:
  datasource:
    url: jdbc:mysql://reconnecting.mysql.database.azure.com:3306/springboot?useSSL=true
    username: reconnecting
    password: I2eNamE2547
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # logging:
  #   level:
  #     root: DEBUG
app:
  token:
    secret: thisIsTopSecret
    issuer: BackendService
